# ./docker-compose.yml

version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootsecretpass
      MYSQL_DATABASE: clase7
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:9906"
  web:
    build:
      context: ./docker/php
    container_name: php_web
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    ports:
      - "8100:80"
    tty: true

volumes:
  db_data:
    